### ISSUE TITLE
Meta shim

### ISSUE THREAD

**Issue by emprove** [quasarframework/app-extension-typescript#15]
I think, we may add default shim for Meta plugin. Something like
```
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    meta?: any;
  }
}
```

**Comment by nothingismagick** [comment]
Thanks for this idea. We'll be looking into it today.

**Comment by nothingismagick** [comment]
We're actually working on removing ALL shims, but I'll leave this issue open until we are able to provide that in beta.

**Comment by nothingismagick** [comment]
Shims are now a thing of the past.
