### ISSUE TITLE
feature request: electron integration

### ISSUE THREAD

**Issue by zrfrank** [quasarframework/app-extension-typescript#19]
Wondering if electron with typescript could be directly supported by this extension.

**Comment by lokingwei** [comment]
+1 for this request, or is there any workaround?

**Comment by outofmemoryagain** [comment]
I have yet to test this scenario, is there a specific issue that you are having?  I wasn't expecting any specific issues with the different modes?  I have test this for PWA and Cordova modes.

**Comment by zrfrank** [comment]
For example,
`quasar create example` with default for all.
`quasar mode add electron`
`quasar ext add @quasar/typescript` with default for all (i.e. rename Yes) 

The file renaming process doesn't cover the `src-electron` folder.

Then, we could manually change the
```
src-electron/main-process/
    electron-main-dev.js --> .ts
    electron-main.js --> .ts
```

If we run `quasar dev -m electron`, there will be error,
```
ERROR in multi ./src-electron/main-process/electron-main.dev.js
Module not found: Error: Can't resolve '/Users/frank/Desktop/example/src-electron/main-process/electron-main.dev.js' in '/Users/frank/Desktop/example'
 @ multi ./src-electron/main-process/electron-main.dev.js electron-main[0]

 app:electron Electron main build failed with errors +0ms
```

I guess the problem could because src-electron is not included in the typescript workflow .

**Comment by outofmemoryagain** [comment]
So there are two issues at hand.  
1. As you have pointed out the rename logic in the extension does not include the src-electron folder.  This is also true for any other src-[mode] directory that is generated outside the main ./src directory.
2. The Quasar CLI currently look for "electron-main.js" and "electron-main.dev.js".  I will verify, but this should be able to be changed to "electron-main" and the file should still be loaded as long as Node module loading strategy is used.

I will focus on the second issue since the first one can be worked around pretty easily.

**Comment by outofmemoryagain** [comment]
Is also possible to work around the second issue by using the Quasar.config.js [sourceFiles](https://quasar.dev/quasar-cli/quasar-conf-js#sourceFiles-Property) to set
```
  electronMainDev: 'src-electron/main-process/electron-main.dev',
  electronMainProd: 'src-electron/main-process/electron-main'
```

A word of caution... I have not tested this yet.

**Comment by zrfrank** [comment]
It might on the right path, there has been a new error.

What I have done,

Add the source files to `Quasar.config`,

```
   sourceFiles: {
      router: 'src/router/index.ts',
      store: 'src/store/index.ts',
      electronMainDev: 'src-electron/main-process/electron-main.dev.ts',
      electronMainProd: 'src-electron/main-process/electron-main.ts'
    },
``` 

Then fixed a few type errors, 

`electron-main.ts`
```ts
// ! I don't know how to fix this error
// Property '__statics' does not exist on type 'Global'.ts(2339)
// so I comment this section out

// if (process.env.PROD) {
//   global.__statics = require('path')
//     .join(__dirname, 'statics')
//     .replace(/\\/g, '\\\\');
// }

let mainWindow: BrowserWindow | null;

function createWindow() {
  /**
   * Initial window options
   */
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    useContentSize: true,
    webPreferences: {
      nodeIntegration: true,
    },
  });

  mainWindow.loadURL(process.env.APP_URL as string);

// rest are the same

```

Then run `quasar dev -m electron`,

```
Dev mode.......... electron
 Pkg quasar........ v1.0.5
 Pkg @quasar/app... v1.0.4
 Debugging......... enabled

 app:extension Running "@quasar/typescript" Quasar App Extension... +0ms
 app:quasar-conf Reading quasar.conf.js +5ms
 app:dev Checking listening address availability (0.0.0.0:8080)... +2ms
 app:webpack Extension(@quasar/typescript): Chaining Renderer process Webpack config +759ms
 app:webpack Extending Renderer process Webpack config +166ms
 app:webpack Extending Main process Webpack config +374ms
 app:generator Generating Webpack entry point +6ms
 app:dev-server Booting up... +2ms

Starting type checking service...
Using 1 worker with 2048MB memory limit

 Renderer process █████████████████████████ [100%] in ~11s
 Main process                               [0%]



 DONE  Compiled successfully in 11104ms                                                                                                       3:45:36 PM

No type errors found
Version: typescript 3.5.3
Time: 3937ms
 app:electron Building main Electron process... +11s

 Renderer process █████████████████████████ [100%] in ~11s
 Main process     █████████████████████████ [100%] in ~96ms

 app:electron Webpack built Electron main process +97ms

Hash: e09721a675a419132165
Version: webpack 4.35.3
Time: 97ms
Built at: 07/16/2019 3:45:36 PM
           Asset      Size         Chunks  Chunk Names
electron-main.js  4.93 KiB  electron-main  electron-main
Entrypoint electron-main = electron-main.js

ERROR in ./src-electron/main-process/electron-main.dev.ts 17:15
Module parse failed: Unexpected token (17:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     .default(installExtension.VUEJS_DEVTOOLS)
|     .then(() => {})
>     .catch((err: any) => {
|       console.log('Unable to install `vue-devtools`: \n', err);
|     });
 @ multi ./src-electron/main-process/electron-main.dev.ts electron-main[0]

 app:electron Electron main build failed with errors +0ms

```

**Comment by outofmemoryagain** [comment]
The first issue you can resolve that by extending the NodeJS Global interface defintion.  Add a new file node.d.ts to your src-electron directory with the following contents
```
declare module NodeJS  {
    interface Global {
        __statics: any
    }
}
```

I will look into the other errors when I have some time.

**Comment by outofmemoryagain** [comment]
Just curious are you planning to write code in these files or are you just trying to remove all JS files from the project?  In general, just to trying to determine how to prioritize this one with some of the other issues logged.

**Comment by zrfrank** [comment]
I'm in no hurry, please feel free to prioritize other more imminent issues.

From a desktop app dev point of view, electron files are heavily scripted. The pure JS works fine, though during app development, typed language can save huge chunk of documentations and avoid many unexpected errors. So it's a feature that's very attractive to app developers.

**Comment by tamasfe** [comment]
It is possible to make webpack work with ts inside `quasar.conf.js` like so:

```
...
electron: {
    chainWebpack(cfg) {
        cfg.resolve.extensions.prepend('.ts').prepend('.tsx');

        cfg.module
            .rule('typescript')
            .test(/\.ts?$/)
            .use('ts-loader')
            .loader('ts-loader')
            .options({
                onlyCompileBundledFiles: true,
                transpileOnly: false
            });
    },
}
...
```

<s>However I can't seem to get it to resolve modules that aren't in `node_modules` correctly. I can store everything in a single file for now, but it's obviously not really ideal.</s>

**edit**:

I can't believe I've spent hours on this, the extensions have to start with "." in order for it to work.

The above code now works flawlessly.

**Comment by IlCallo** [comment]
Electron integration typings are now provided by `@quasar/app`, even if I'm not sure if I understood correctly what you were requesting.
If not, please open a new issue on Quasar main repo, this AE is now deprecated
