### ISSUE TITLE
solution for vscode adding semicolon in ts based single file components.

### ISSUE THREAD

**Issue by paulvanbladel** [quasarframework/app-extension-typescript#21]
Even if in   "prettier.semi": false is specified in vsCode settings json file,  vscode will add semicolon in the ts part.
This can be avoided when specifying:
  "vetur.format.defaultFormatterOptions": {
    "prettier": {
      "stylelintIntegration": true,
      "eslintIntegration": true,
      "semi": false,
      "singleQuote": true,
      "tabWidth": 2
    }
  }

**Comment by IlCallo** [comment]
You should install Prettier extension and add a `.prettierrc` file at root level with the preferred settings.
Vetur is just using prettier under the hood, unless you tell him to use another formatter or you are formatting HTML, for which the default is not Prettier.

VSCode `settings.json` is not the right place to put Prettier configuration

**Comment by outofmemoryagain** [comment]
@paulvanbladel Please verify if the solution suggested by @IlCallo resolves your issue and if so, close this issue.
