### ISSUE TITLE
Package manager detection

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/app-extension-typescript#27]
If we really need to put some dependencies into the project `package.json` and sequentially run `yarn` or `npm` to install them, we should detect in some way which package manages has been used.

[Here](https://github.com/quasarframework/quasar/blob/dev/cli/lib/node-packager.js#L18) is how the core package does it.
Maybe adding that function to AE install API could be a way, to avoid redundance.

**Comment by nothingismagick** [comment]
That's done automatically if we add to the package.json

**Comment by nothingismagick** [comment]
See my comment here:
https://github.com/quasarframework/app-extension-typescript/pull/22#issuecomment-513835023

**Comment by IlCallo** [comment]
Saw that, but until you discuss it further, I was listing all issues we gathered in these two weeks to look at them in isolation.
On the other side, `@types/node` was added to the user project and installed with `yarn` before I touched the code, so maybe there is a valid use case to use `updatePackageJson`
