### ISSUE TITLE
Move TS support to main repo

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/app-extension-typescript#28]
TypeScript is trasversal to many concerns in a project and is difficult to integrate if it's not done at creation time in the main repo.

The AE should serve as a migration tool for already existing projects.

**Comment by outofmemoryagain** [comment]
This Feature request exists on the main Quasar repo https://github.com/quasarframework/quasar/issues/4399

**Comment by paulvanbladel** [comment]
Maybe same concern for testing. TS extension ok. Testing extension Ok. But when you install both ts and testing: not ok and wallaby fails.

**Comment by outofmemoryagain** [comment]
This is known and there is a [pending issue](https://github.com/quasarframework/quasar-testing/issues/48) in the Testing extension to resolve this.  Thanks to @IlCallo for getting this effort started.

**Comment by IlCallo** [comment]
TS is now natively supported into Quasar core
