### ISSUE TITLE
Linting vue is slow

### ISSUE THREAD

**Issue by razbakov** [quasarframework/app-extension-typescript#32]
### Steps to reproduce

1. Create a new project:

```
quasar create example
cd example
quasar ext add @quasar/typescript
```

2. Fix all the errors (see #31)

### without vue < 5 sec

```
eslint --ext .js,.ts --ignore-path .gitignore ./
```

✨  Done in 3.85s.

### with vue > 5 sec

```
eslint --ext .js,.ts,.vue --ignore-path .gitignore ./
```

✨  Done in 8.55s.

**Comment by IlCallo** [comment]
Should be solved when we move to `typescript-eslint` v2, but there are some problems we must tackle first: https://github.com/quasarframework/app-extension-typescript/issues/23

**Comment by Maissacrement** [comment]
You can specify what are you linitng too, can you try add './src' ?

`eslint --ext .js,.ts,.vue --ignore-path .gitignore ./src`

**Comment by IlCallo** [comment]
`typescript-eslint` v2 has been integrated and linting should be much faster than before
