### ISSUE TITLE
Extending the .vscode/settings.json fails if it's JSON5

### ISSUE THREAD

**Issue by rmehner** [quasarframework/app-extension-typescript#42]
👋 ,

I've stumbled across an issue trying to install this package with: `quasar ext add @quasar/typescript`.

When I choose "Yes" for the VSCode question, the installer bails out with this error:

`UnhandledPromiseRejectionWarning:   SyntaxError: vscode/settings.json: Unexpected token } in JSON at position 524`

This is caused by a trailing comma in the existing `settings.json`:

```json5
{
  "[vue]": {
    "editor.formatOnSave": true,
    // trailing comma here
    "editor.formatOnPaste": true,
  },
  "eslint.validate": [
      "javascript",
      "javascriptreact",
      "vue"
  ]
}

```

This is not valid JSON, but it is valid [JSON5](https://json5.org) which VSCode is using for their setting files.

Full Log:
<details>
? Please choose how to derive webpack: Use the fork-ts-checker-webpack-plugin module for type-checking (recommended)
? Rename .js files to .ts (experimental) Yes
? Will you use VSCode for this project? (Adds ESLint and Vetur configuration quirks, you must manually install the extensions) Yes
? Generate prettier configuration (ESLint and VScode, if used)? Yes

 app:extension-manager Updating /quasar.extensions.json for "@quasar/typescript" extension ... +21s
 app:extension Running App Extension install script... +16ms
(node:21189) UnhandledPromiseRejectionWarning:   SyntaxError: vscode/settings.json: Unexpected token } in JSON at position 524

  - JSON.parse

  - loader.js:987 Object.Module._extensions..json
    internal/modules/cjs/loader.js:987:27

  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32

  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14

  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19

  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18

  - InstallAPI.js:214 InstallAPI.extendJsonFile
    [frontend]/[@quasar]/app/lib/app-extension/InstallAPI.js:214:48

  - install.js:42 module.exports
    [frontend]/[@quasar]/quasar-app-extension-typescript/src/install.js:42:9

  - Extension.js:326 Extension.__runInstallScript
    [frontend]/[@quasar]/app/lib/app-extension/Extension.js:326:11

  - Extension.js:163 Extension.install
    [frontend]/[@quasar]/app/lib/app-extension/Extension.js:163:30

(node:21189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>

Thanks for reading and have a great day!

**Comment by IlCallo** [comment]
This issue is more about quasar InstallAPI than this extension in particular. May you close this issue and open a new one on the main repo, referencing this one?

**Comment by rmehner** [comment]
Done, have a nice day :)
