### ISSUE TITLE
performance problem when using @quasar/typescript

### ISSUE THREAD

**Issue by alirezajs** [quasarframework/app-extension-typescript#47]
Since I added `@quasar/typescript` for using typescript in my project, my debug is quite slow, some time for `quasar dev` I should wait around 10 minutes, furthermore, after running when I save my changes I have to wait at least 30 seconds to see my changes. 

> because I'm working on a project with a limited deadline, it is an acute problem for me

**Comment by Maissacrement** [comment]
Same in @quasar/typescript

**Comment by Maissacrement** [comment]
> Since I added `@quasar/typescript` for using typescript in my project, my debug is quite slow, some time for `quasar dev` I should wait around 10 minutes, furthermore, after running when I save my changes I have to wait at least 30 seconds to see my changes.
> 
> > because I'm working on a project with a limited deadline, it is an acute problem for me

After a research i found a solution for fast dev build with `@quasar/typescript` :

https://github.com/IlCallo/quasar-typescript-starter/blob/master/quasar.conf.js

https://quasar.dev/quasar-cli/cli-documentation/handling-webpack

https://github.com/neutrinojs/webpack-chain

It is not necessary to create a quasar.conf.ts nevertheless you need too optimized your tsconfig.json file

before compiling : ~11m 
now compiling: ~1m

**Comment by rstoenescu** [comment]
@quasar/typescript is soon to be deprecated. Please upgrade your Quasar dependencies and use the embedded support --> https://quasar.dev/quasar-cli/cli-documentation/supporting-ts
