### ISSUE TITLE
Converting all files converts store / router and shouldn't

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-typescript#5]
It seems router / store require there to be an index.js file so perhaps it shouldn't rename them.

**Comment by nklayman** [comment]
The `sourceFiles` attribute should be added to your `quasar.conf.js` so that it will use the TS variants.

**Comment by nklayman** [comment]
If it can't do that automatically, it should notify you and ask you to put it in manually.

**Comment by nothingismagick** [comment]
I believe this happened because he chose "not to transform to ts"

**Comment by webnoob** [comment]
Yeah sorry this is a dupe really: https://github.com/quasarframework/app-extension-typescript/issues/6

**Comment by nklayman** [comment]
Closed in favor of #6.
