### ISSUE TITLE
If you choose not to rename files then quasar conf options can be wrong

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-typescript#6]
The install adds:

```js
sourceFiles: {
      router: 'src/router/index.ts',
      store: 'src/store/index.ts'
    }
```

But if you select no to the file conversion, it'll omit the `.ts` and can potentially break the build.

This should either be accounted for (i.e check if route/index is js or ts) or at least warn the users in the docs.

**Comment by nklayman** [comment]
I agree, we should probably mention this in the docs.

**Comment by IlCallo** [comment]
Quasar now accept both `js` and `ts` extension for router and store files, this should not be a problem anymore
