### ISSUE TITLE
Boot files cannot be .ts files

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-typescript#7]
When all the files get renamed, it renames boot files to .ts which would be great but they can't be TS files. It seems Quasar looks for js files.

**Comment by nklayman** [comment]
Seems like this might be an issue with `@quasar/app` as it handles the resolving of boot files.

**Comment by webnoob** [comment]
Yeah I agree.
Perhaps not changing the boot file types for now would be a good thing?

**Comment by nothingismagick** [comment]
what happens if you name the bootfile in quasar.conf e.g.
boot: ['i18n.ts']

>

**Comment by webnoob** [comment]
Not in a position to test this just yet. Will try ASAP.

**Comment by webnoob** [comment]
Yes, this appears to work so on install the extension should rename the files (if the user selects) and then rename these options in the quasar.conf.file.

**Comment by nothingismagick** [comment]
YAY! I was right about something!!!

>

**Comment by nklayman** [comment]
This might be tricky to rename. Should I parse the JSON and re-write it?

**Comment by webnoob** [comment]
What do you do for the `sourceFile` parts? Just prepend?

**Comment by nklayman** [comment]
I use a regex to find the `module.exports = function () {...`

**Comment by webnoob** [comment]
I see 2 options, 

1. Parse the JSON
2. Keep track of the boot files you rename and then string replace them in the file (definitely a nasty idea)

I'd prefer a message to the user to do it themselves over 2 TBH.

**Comment by dboune** [comment]
I am not yet using `app-extension-typescript`, and had no trouble refactoring the boot files for TypeScript.

At least in the `@quasar/app: 1.0.0-beta.10` the import of the boot files looks like...

client-entry.js and server-entry.js in `@quasar/app/templates/entry`
```
import <%= importName %> from 'boot/<%= asset.path %>'
```

So it treats them as modules.. no .js or .ts. Webpack won't care, and will just process them as directed in config.

**Comment by nklayman** [comment]
That is probably the best option as it removes the need to mess with the config and allows for easy switching between `.js` and `.ts`.

**Comment by webnoob** [comment]
Yeah, I now think this was down to other issues with the loader rather than something that needs fixing.
