### ISSUE TITLE
tsconfig.json needs baseUrl

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-typescript#8]
It needs `"baseUrl": "."` so that module resolution will work correctly. I think it might also need some bits to make webpack aliases work but I'll update as I find out more.

**Comment by dboune** [comment]
I am not yet using `app-extension-typescript`.

I am using `"@quasar/app": "1.0.0-beta.10"` with TypeScript.

Here is my initial `tsconfig.json`, which appears to be functioning correctly. I need to tune lib a bit more, but what is below is what was needed to get everything working comfortably "out-of-the-box".

_tsconfig.json_
```json5
{
  "compilerOptions": {
    "target": "es5",
    "module": "ESNext", // ESNext required for dynamic import used in routes.ts
    "lib": [
      "dom",       // Browser DOM
      "webworker", // Browser WebWorkers
      "es2015"     // Required for Promise
    ],
    "strict": true,
    "moduleResolution": "node", // Must be explicitly set to "node" when module is set to "es2015" or "esNext",
    "baseUrl": ".",
    "paths": {
      "*": [
        "*"
      ]
    },
    "esModuleInterop": true,
    "experimentalDecorators": true, // For use with vue-class-component / vue-property-decorator / vuex-class
}
```
