### ISSUE TITLE
Non-Critical: VUE_ROUTER_BASE is string

### ISSUE THREAD

**Issue by dboune** [quasarframework/app-extension-typescript#9]
Not a critical issue.

`VUE_ROUTER_BASE` is simply a string or undefined.

**Reference:** https://router.vuejs.org/api/#base

https://github.com/quasarframework/app-extension-typescript/blob/af768219830c1c6188588e49ed4f7f0409cd68cd/extension/src/templates/base/src/env.d.ts#L5

**Comment by nklayman** [comment]
Thanks for the tip!
